2024-12-04 22:49:00 ERROR 400 response executing GraphQL.
2024-12-04 22:49:00 ERROR {"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: learning_rate","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-12-04 22:49:00 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 887, in sweep
    sweep_id, warnings = api.upsert_sweep(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 133, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 57, in wrapper
    raise err
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3340, in upsert_sweep
    raise e
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3334, in upsert_sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\util.py", line 880, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Invalid sweep config: invalid hyperparameter configuration: learning_rate

2024-12-04 22:54:59 ERROR 400 response executing GraphQL.
2024-12-04 22:54:59 ERROR {"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: learning_rate","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-12-04 22:54:59 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 887, in sweep
    sweep_id, warnings = api.upsert_sweep(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 133, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 57, in wrapper
    raise err
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3340, in upsert_sweep
    raise e
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3334, in upsert_sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\util.py", line 880, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Invalid sweep config: invalid hyperparameter configuration: learning_rate

2024-12-04 22:55:25 ERROR 400 response executing GraphQL.
2024-12-04 22:55:25 ERROR {"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: learning_rate","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-12-04 22:55:25 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 887, in sweep
    sweep_id, warnings = api.upsert_sweep(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 133, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 57, in wrapper
    raise err
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3340, in upsert_sweep
    raise e
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3334, in upsert_sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\util.py", line 880, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Invalid sweep config: invalid hyperparameter configuration: learning_rate

2024-12-04 22:56:11 ERROR 400 response executing GraphQL.
2024-12-04 22:56:11 ERROR {"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: weight_decay","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-12-04 22:56:11 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 887, in sweep
    sweep_id, warnings = api.upsert_sweep(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 133, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 57, in wrapper
    raise err
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3340, in upsert_sweep
    raise e
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3334, in upsert_sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\util.py", line 880, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Invalid sweep config: invalid hyperparameter configuration: weight_decay

2024-12-04 23:01:39 ERROR 400 response executing GraphQL.
2024-12-04 23:01:39 ERROR {"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: weight_decay","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-12-04 23:01:39 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 887, in sweep
    sweep_id, warnings = api.upsert_sweep(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 133, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 57, in wrapper
    raise err
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3340, in upsert_sweep
    raise e
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3334, in upsert_sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\util.py", line 880, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Invalid sweep config: invalid hyperparameter configuration: weight_decay

2024-12-04 23:02:03 ERROR 400 response executing GraphQL.
2024-12-04 23:02:03 ERROR {"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: weight_decay","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-12-04 23:02:03 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 887, in sweep
    sweep_id, warnings = api.upsert_sweep(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 133, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 57, in wrapper
    raise err
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3340, in upsert_sweep
    raise e
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3334, in upsert_sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\util.py", line 880, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Invalid sweep config: invalid hyperparameter configuration: weight_decay

2024-12-04 23:05:58 ERROR 400 response executing GraphQL.
2024-12-04 23:05:58 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-04 23:05:58 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-04 23:07:10 ERROR 400 response executing GraphQL.
2024-12-04 23:07:10 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-04 23:07:10 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-04 23:08:59 ERROR 400 response executing GraphQL.
2024-12-04 23:08:59 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-04 23:08:59 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-04 23:10:25 ERROR 400 response executing GraphQL.
2024-12-04 23:10:25 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-04 23:10:25 ERROR Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\OneDrive - Danmarks Tekniske Universitet\Master Thesis\.venv\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-04 23:21:01 INFO Running runs: []
2024-12-04 23:21:01 INFO Agent received command: run
2024-12-04 23:21:01 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.002781042274678537
	num_layers: 4
	optimizer: AdamW
	weight_decay: 1.2880851611385489e-10
2024-12-04 23:21:01 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.002781042274678537 --num_layers=4 --optimizer=AdamW --weight_decay=1.2880851611385489e-10
2024-12-04 23:21:06 INFO Running runs: ['1gz6civ2']
2024-12-04 23:21:42 INFO Cleaning up finished run: 1gz6civ2
2024-12-04 23:21:43 INFO Agent received command: run
2024-12-04 23:21:43 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.00023821311900009835
	num_layers: 4
	optimizer: AdamW
	weight_decay: 9.72830762359407e-08
2024-12-04 23:21:43 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.00023821311900009835 --num_layers=4 --optimizer=AdamW --weight_decay=9.72830762359407e-08
2024-12-04 23:21:48 INFO Running runs: ['5j414us0']
2024-12-04 23:22:24 INFO Cleaning up finished run: 5j414us0
2024-12-04 23:22:24 INFO Agent received command: run
2024-12-04 23:22:24 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.0016407256989791983
	num_layers: 4
	optimizer: AdamW
	weight_decay: 7.271953532963932e-05
2024-12-04 23:22:24 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.0016407256989791983 --num_layers=4 --optimizer=AdamW --weight_decay=7.271953532963932e-05
2024-12-04 23:22:29 INFO Running runs: ['fldoq99b']
2024-12-04 23:23:05 INFO Cleaning up finished run: fldoq99b
2024-12-04 23:23:05 INFO Agent received command: run
2024-12-04 23:23:05 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.0005247894782974927
	num_layers: 4
	optimizer: AdamW
	weight_decay: 0.0033734944215164176
2024-12-04 23:23:05 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.0005247894782974927 --num_layers=4 --optimizer=AdamW --weight_decay=0.0033734944215164176
2024-12-04 23:23:10 INFO Running runs: ['z6cnl82s']
2024-12-04 23:23:10 INFO Cleaning up finished run: z6cnl82s
2024-12-04 23:23:11 INFO Agent received command: run
2024-12-04 23:23:11 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.0014298500653998918
	num_layers: 4
	optimizer: AdamW
	weight_decay: 9.007673535648323e-10
2024-12-04 23:23:11 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.0014298500653998918 --num_layers=4 --optimizer=AdamW --weight_decay=9.007673535648323e-10
2024-12-04 23:23:16 INFO Running runs: ['pzvjmbp0']
2024-12-04 23:24:48 INFO Running runs: []
2024-12-04 23:24:48 INFO Agent received command: run
2024-12-04 23:24:48 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.004595290065329516
	num_layers: 4
	optimizer: AdamW
	weight_decay: 0.004243551413027796
2024-12-04 23:24:48 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.004595290065329516 --num_layers=4 --optimizer=AdamW --weight_decay=0.004243551413027796
2024-12-04 23:24:53 INFO Running runs: ['1zfqz9zw']
2024-12-04 23:24:53 INFO Cleaning up finished run: 1zfqz9zw
2024-12-04 23:24:54 INFO Agent received command: run
2024-12-04 23:24:54 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.0024456664241947436
	num_layers: 4
	optimizer: AdamW
	weight_decay: 1.4307963331657946e-12
2024-12-04 23:24:54 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.0024456664241947436 --num_layers=4 --optimizer=AdamW --weight_decay=1.4307963331657946e-12
2024-12-04 23:24:59 INFO Running runs: ['f5g0f1dg']
2024-12-04 23:25:04 INFO Cleaning up finished run: f5g0f1dg
2024-12-04 23:25:05 INFO Agent received command: run
2024-12-04 23:25:05 INFO Agent starting run with config:
	epochs: 10000
	hidden_size: 16
	learning_rate: 0.001361373805000009
	num_layers: 4
	optimizer: AdamW
	weight_decay: 0.006159382198150689
2024-12-04 23:25:05 INFO About to run command: python scripts/SweepLV.py --epochs=10000 --hidden_size=16 --learning_rate=0.001361373805000009 --num_layers=4 --optimizer=AdamW --weight_decay=0.006159382198150689
2024-12-04 23:25:10 INFO Running runs: ['qioiizde']
2024-12-04 23:25:10 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2024-12-04 23:25:10 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
